### ISSUE TITLE
Unable to create file

### ISSUE THREAD

**Issue by Grumlern** [techbliss/EHF_attachment_converter#1]
![error - ehf xml to pdf](https://user-images.githubusercontent.com/33892456/33116877-c0d01274-cf66-11e7-91e4-fe5c2fceceb7.PNG)

Hi,

I am not certain if I am doing something wrong or if it is not working as intended. Programming is not my strong suit, so the lines it is printing does not make sense to me. hope you are able to suggest a solution :)

I did not have Python installed, so had to install it. it recides under the following path if it might create implications: "C:\Users\[username]\AppData\Local\Programs\Python\Python37-32"

BR Grumlern

**Comment by techbliss** [comment]
the command is Convert_attachment.py infile.xml , or drag drop xml file into the py file.
and offcourse the string "cbc:EmbeddedDocumentBinaryObject" must be in the xml file, since its there the base64 attachment are located.

**Comment by Grumlern** [comment]
Lacking knowledge on my part. Seems our provider does not include any base64 string in the XML file, thus unable to create a PDF file with any data. Thank you for the reply and clarification.
